/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cohort {
  'members' : Array<CohortMember>,
  'owner' : Principal,
  'createdAt' : Time,
}
export interface CohortMember { 'principal' : Principal, 'role' : MemberRole }
export interface DiscountRates {
  'trial' : bigint,
  'patronPro' : bigint,
  'cohort' : bigint,
  'sponsorClient' : bigint,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export type MemberCategory = { 'trial' : null } |
  { 'premium' : null } |
  { 'standard' : null };
export type MemberRole = { 'professional' : null } |
  { 'friend' : null } |
  { 'family' : null };
export interface MembershipState {
  'badgeMinted' : boolean,
  'category' : MemberCategory,
  'trialEndsAt' : [] | [Time],
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface SavedCatalogItem {
  'itemId' : string,
  'title' : string,
  'description' : string,
  'imageUrl' : string,
  'savedAt' : Time,
  'category' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCohort' : ActorMethod<[Array<CohortMember>], undefined>,
  'createTrialMembership' : ActorMethod<[], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllMemberships' : ActorMethod<[], Array<MembershipState>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getCallerMembershipState' : ActorMethod<[], MembershipState>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCohort' : ActorMethod<[], [] | [Cohort]>,
  'getDiscountRates' : ActorMethod<[], DiscountRates>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getMemberCohort' : ActorMethod<[Principal], Cohort>,
  'getMembershipState' : ActorMethod<[Principal], MembershipState>,
  'getSavedCatalogItems' : ActorMethod<[], Array<SavedCatalogItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasAnyAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAdmins' : ActorMethod<[], Array<string>>,
  'mintBadge' : ActorMethod<[], undefined>,
  'registerAsFirstAdmin' : ActorMethod<[], undefined>,
  'removeAdmin' : ActorMethod<[Principal], undefined>,
  'removeSavedCatalogItem' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCatalogItem' : ActorMethod<[SavedCatalogItem], undefined>,
  'setDiscountRates' : ActorMethod<[DiscountRates], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'upgradeToPremium' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];