/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cohort {
  'members' : Array<CohortMember>,
  'owner' : Principal,
  'createdAt' : Time,
}
export interface CohortMember { 'principal' : Principal, 'role' : MemberRole }
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export type MemberCategory = { 'trial' : null } |
  { 'premium' : null } |
  { 'standard' : null };
export type MemberRole = { 'professional' : null } |
  { 'friend' : null } |
  { 'family' : null };
export interface MembershipState {
  'badgeMinted' : boolean,
  'category' : MemberCategory,
  'trialEndsAt' : [] | [Time],
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCohort' : ActorMethod<[Array<CohortMember>], undefined>,
  'createTrialMembership' : ActorMethod<[], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllMemberships' : ActorMethod<[], Array<MembershipState>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getCallerMembershipState' : ActorMethod<[], MembershipState>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCohort' : ActorMethod<[], [] | [Cohort]>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getMemberCohort' : ActorMethod<[Principal], Cohort>,
  'getMembershipState' : ActorMethod<[Principal], MembershipState>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'mintBadge' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'upgradeToPremium' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];