/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MemberRole = IDL.Variant({
  'professional' : IDL.Null,
  'friend' : IDL.Null,
  'family' : IDL.Null,
});
export const CohortMember = IDL.Record({
  'principal' : IDL.Principal,
  'role' : MemberRole,
});
export const MemberCategory = IDL.Variant({
  'trial' : IDL.Null,
  'premium' : IDL.Null,
  'standard' : IDL.Null,
});
export const Time = IDL.Int;
export const MembershipState = IDL.Record({
  'badgeMinted' : IDL.Bool,
  'category' : MemberCategory,
  'trialEndsAt' : IDL.Opt(Time),
});
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Cohort = IDL.Record({
  'members' : IDL.Vec(CohortMember),
  'owner' : IDL.Principal,
  'createdAt' : Time,
});
export const DiscountRates = IDL.Record({
  'trial' : IDL.Nat,
  'patronPro' : IDL.Nat,
  'cohort' : IDL.Nat,
  'sponsorClient' : IDL.Nat,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const SavedCatalogItem = IDL.Record({
  'itemId' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'savedAt' : Time,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addAdmin' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCohort' : IDL.Func([IDL.Vec(CohortMember)], [], []),
  'createTrialMembership' : IDL.Func([], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllMemberships' : IDL.Func([], [IDL.Vec(MembershipState)], ['query']),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getCallerMembershipState' : IDL.Func([], [MembershipState], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCohort' : IDL.Func([], [IDL.Opt(Cohort)], ['query']),
  'getDiscountRates' : IDL.Func([], [DiscountRates], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getMemberCohort' : IDL.Func([IDL.Principal], [Cohort], ['query']),
  'getMembershipState' : IDL.Func(
      [IDL.Principal],
      [MembershipState],
      ['query'],
    ),
  'getSavedCatalogItems' : IDL.Func([], [IDL.Vec(SavedCatalogItem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasAnyAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAdmins' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'mintBadge' : IDL.Func([], [], []),
  'registerAsFirstAdmin' : IDL.Func([], [], []),
  'removeAdmin' : IDL.Func([IDL.Principal], [], []),
  'removeSavedCatalogItem' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCatalogItem' : IDL.Func([SavedCatalogItem], [], []),
  'setDiscountRates' : IDL.Func([DiscountRates], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'upgradeToPremium' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MemberRole = IDL.Variant({
    'professional' : IDL.Null,
    'friend' : IDL.Null,
    'family' : IDL.Null,
  });
  const CohortMember = IDL.Record({
    'principal' : IDL.Principal,
    'role' : MemberRole,
  });
  const MemberCategory = IDL.Variant({
    'trial' : IDL.Null,
    'premium' : IDL.Null,
    'standard' : IDL.Null,
  });
  const Time = IDL.Int;
  const MembershipState = IDL.Record({
    'badgeMinted' : IDL.Bool,
    'category' : MemberCategory,
    'trialEndsAt' : IDL.Opt(Time),
  });
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Cohort = IDL.Record({
    'members' : IDL.Vec(CohortMember),
    'owner' : IDL.Principal,
    'createdAt' : Time,
  });
  const DiscountRates = IDL.Record({
    'trial' : IDL.Nat,
    'patronPro' : IDL.Nat,
    'cohort' : IDL.Nat,
    'sponsorClient' : IDL.Nat,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const SavedCatalogItem = IDL.Record({
    'itemId' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'savedAt' : Time,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addAdmin' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCohort' : IDL.Func([IDL.Vec(CohortMember)], [], []),
    'createTrialMembership' : IDL.Func([], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllMemberships' : IDL.Func([], [IDL.Vec(MembershipState)], ['query']),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getCallerMembershipState' : IDL.Func([], [MembershipState], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCohort' : IDL.Func([], [IDL.Opt(Cohort)], ['query']),
    'getDiscountRates' : IDL.Func([], [DiscountRates], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getMemberCohort' : IDL.Func([IDL.Principal], [Cohort], ['query']),
    'getMembershipState' : IDL.Func(
        [IDL.Principal],
        [MembershipState],
        ['query'],
      ),
    'getSavedCatalogItems' : IDL.Func(
        [],
        [IDL.Vec(SavedCatalogItem)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasAnyAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAdmins' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'mintBadge' : IDL.Func([], [], []),
    'registerAsFirstAdmin' : IDL.Func([], [], []),
    'removeAdmin' : IDL.Func([IDL.Principal], [], []),
    'removeSavedCatalogItem' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCatalogItem' : IDL.Func([SavedCatalogItem], [], []),
    'setDiscountRates' : IDL.Func([DiscountRates], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'upgradeToPremium' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };