/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MemberCategory = IDL.Variant({
  'trial' : IDL.Null,
  'premium' : IDL.Null,
  'standard' : IDL.Null,
});
export const Time = IDL.Int;
export const MembershipState = IDL.Record({
  'category' : MemberCategory,
  'nftMinted' : IDL.Bool,
  'trialEndsAt' : IDL.Opt(Time),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTrialMembership' : IDL.Func([], [], []),
  'getAllMemberships' : IDL.Func([], [IDL.Vec(MembershipState)], ['query']),
  'getCallerMembershipState' : IDL.Func([], [MembershipState], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMembershipState' : IDL.Func(
      [IDL.Principal],
      [MembershipState],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'mintMembership' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'upgradeToPremium' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MemberCategory = IDL.Variant({
    'trial' : IDL.Null,
    'premium' : IDL.Null,
    'standard' : IDL.Null,
  });
  const Time = IDL.Int;
  const MembershipState = IDL.Record({
    'category' : MemberCategory,
    'nftMinted' : IDL.Bool,
    'trialEndsAt' : IDL.Opt(Time),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTrialMembership' : IDL.Func([], [], []),
    'getAllMemberships' : IDL.Func([], [IDL.Vec(MembershipState)], ['query']),
    'getCallerMembershipState' : IDL.Func([], [MembershipState], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMembershipState' : IDL.Func(
        [IDL.Principal],
        [MembershipState],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'mintMembership' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'upgradeToPremium' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };